_wandb:
    value:
        cli_version: 0.23.1
        e:
            1ytkhecum32g7uksqeuoffc0o9fhecbu:
                args:
                    - --epochs
                    - "5"
                    - --batch_size
                    - "64"
                    - --lr
                    - "5e-4"
                    - --dataset_dir
                    - data_for_pretrain/Faced/processed
                    - --model_dir
                    - model_dir/pretrained_faced_model
                    - --mamba_global
                    - "False"
                    - --depths
                    - 1,1
                    - --stage_types
                    - mamba,attn
                codePath: pretrain_main.py
                codePathLocal: pretrain_main.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "137322156032"
                email: 1421816607@qq.com
                executable: /home/springrain-i/BaseLine/venv/bin/python
                git:
                    commit: 17d1af0d8ba2fcc89fb4871b18a24f63376066a1
                    remote: git@github.com:springrain-i/BraMT.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-5b27cb50-3240-f7c3-d0d7-a8b590753c2f
                host: qixu
                memory:
                    total: "8182214656"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/springrain-i/BaseLine/pretrain_main.py
                python: CPython 3.12.8
                root: ./wandb
                startedAt: "2025-12-21T11:11:04.513005Z"
                writerId: 1ytkhecum32g7uksqeuoffc0o9fhecbu
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
            "3":
                - 1
                - 13
                - 16
            "4": 3.12.8
            "5": 0.23.1
            "6": 4.56.2
            "12": 0.23.1
            "13": linux-x86_64
axis_order:
    value: true
batch_size:
    value: 64
clip_value:
    value: 1
conv_bias:
    value: true
cuda:
    value: 0
d_conv:
    value: 4
d_model:
    value: 200
d_state:
    value: 16
dataset_dir:
    value: data_for_pretrain/Faced/processed
depths:
    value: 1,1
dim_feedforward:
    value: 800
dropout:
    value: 0.1
epochs:
    value: 5
expand:
    value: 2
in_dim:
    value: 200
log_dir:
    value: ./logs
lr:
    value: 0.0005
lr_scheduler:
    value: CosineAnnealingLR
mamba_global:
    value: true
mask_ratio:
    value: 0.5
model_dir:
    value: model_dir/pretrained_faced_model
need_mask:
    value: true
nhead:
    value: 8
out_dim:
    value: 200
parallel:
    value: false
seed:
    value: 42
seq_len:
    value: 30
stage_types:
    value: mamba,attn
use_wandb:
    value: true
wandb_dir:
    value: ./wandb
wandb_entity:
    value: null
wandb_mode:
    value: online
wandb_project:
    value: eeg-pretrain
weight_decay:
    value: 0.05
